In [33]:
# Import all required libraries

import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import matplotlib.pyplot as plt
import seaborn as sns
from numpy import vectorize

In [34]:
df=pd.read_csv('/content/sample_data/UpdatedResumeDataSet.csv')
df.shape

(962, 2)

In [35]:
df.head()

       Category                                             Resume
0  Data Science  Skills * Programming Languages: Python (pandas...
1  Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
2  Data Science  Areas of Interest Deep Learning, Control Syste...
3  Data Science  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
4  Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...

In [36]:
print('\n Columns',df.columns.tolist())

 Columns ['Category', 'Resume']

In [37]:
sample_df=df.sample(10,random_state=42).reset_index(drop=True)
sample_df.head()

             Category                                             Resume
0      Java Developer  TECHNICAL SKILLS Programming Languages: Java (...
1      Java Developer  TECHNICALSKILLS SpringMVC, Hibernate, JDBC, Ja...
2      Java Developer  Education Details \r\nJanuary 2013 Master of E...
3              Hadoop  Skill Set: Hadoop, Map Reduce, HDFS, Hive, Sqo...
4  Health and fitness  Education Details \r\nJanuary 1992 to January ...

In [38]:
sample_df=sample_df.rename(columns={'Resume':'resume_text'})
sample_df.shape

(10, 2)

In [39]:
vectorizer=TfidfVectorizer(stop_words='english')
tfidf_matrix=vectorizer.fit_transform(sample_df['resume_text'])
tfidf_matrix.shape

(10, 1125)

In [40]:
similarities_matrix=cosine_similarity(tfidf_matrix)
sim_df=pd.DataFrame(similarities_matrix,index=sample_df['Category']+'_'+sample_df.index.astype(str),
                    columns=sample_df['Category']+'_'+sample_df.index.astype(str))
sim_df.round(2).head(3)

                  Java Developer_0  ...  Health and fitness_9
Java Developer_0              1.00  ...                  0.08
Java Developer_1              0.41  ...                  0.06
Java Developer_2              0.24  ...                  0.03

[3 rows x 10 columns]

In [49]:
resume={
    'candidate':['Lily','Molly','Polly'],
    'resume_text':['Python developer skilled in Django,Flask, Rest API ans MySQL',
                   'Machine learning engineer experience in Python, TensorFlow, NLP and data analysis',
                   'Full stack developer with .net, javascript, React, Node.js and MongoDB experience']

}

In [57]:
df=pd.DataFrame(resume)
df

  candidate                                        resume_text
0      Lily  Python developer skilled in Django,Flask, Rest...
1     Molly  Machine learning engineer experience in Python...
2     Polly  Full stack developer with .net, javascript, Re...

In [59]:
vectorizer=TfidfVectorizer(stop_words='english')
tfidf_matrix=vectorizer.fit_transform(df['resume_text'])
tfidf_matrix.shape
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 27 stored elements and shape (3, 24)>

In [60]:
similarities_matrix=cosine_similarity(tfidf_matrix)
sim_df=pd.DataFrame(similarities_matrix,index=df['candidate'],columns=df['candidate'])
sim_df.round(2)

candidate  Lily  Molly  Polly
candidate
Lily       1.00   0.07   0.07
Molly      0.07   1.00   0.07
Polly      0.07   0.07   1.00

In [65]:
df.loc[len(df)]=["Zoya","Backend developer skilled in Python, Flask and SQL"]

In [66]:
df

  candidate                                        resume_text
0      Lily  Python developer skilled in Django,Flask, Rest...
1     Molly  Machine learning engineer experience in Python...
2     Polly  Full stack developer with .net, javascript, Re...
3      Zoya  Backend developer skilled in Python, Flask and...

In [67]:
vectorizer=TfidfVectorizer(stop_words='english')
tfidf_matrix=vectorizer.fit_transform(df['resume_text'])
tfidf_matrix.shape
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 33 stored elements and shape (4, 26)>

In [68]:
similarities_matrix=cosine_similarity(tfidf_matrix)
sim_df=pd.DataFrame(similarities_matrix,index=df['candidate'],
                    columns=df['candidate'])
sim_df.round(2)

candidate  Lily  Molly  Polly  Zoya
candidate
Lily       1.00   0.05   0.05  0.38
Molly      0.05   1.00   0.08  0.07
Polly      0.05   0.08   1.00  0.07
Zoya       0.38   0.07   0.07  1.00