**Steps for Modeling**

  1.Creating the model
  2.Compiling the model.
  3.Define a loss function.
  4.Setting up an optimizer.
  5.Finding best learning size.
  6.Creating Evaluation matrics
  7.Fitting Model
  8.Improve Model

# Predict Heart Disease
  1.Load Dataset
  2.Split Features and Test
  3.Train Test Split
  4.Scale Features

In [35]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [36]:
heart_data=pd.read_csv('/content/sample_data/heart.csv')
heart_data.head()

   age  sex  chol  trestbps  thalach  target
0   52    1   200       130      150       1
1   58    0   240       150      140       1
2   60    1   180       140      145       0
3   48    1   190       120      160       0
4   50    0   220       125      155       1

In [37]:
x=heart_data.drop('target',axis=1)
y=heart_data['target']

In [38]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [39]:
scalar=StandardScaler()
x_train_scaled=scalar.fit_transform(x_train)
x_test_scaled=scalar.transform(x_test)

In [40]:
model=tf.keras.Sequential(
    [
     tf.keras.layers.Dense(16,activation='relu',input_shape=(x_train.shape[1],)),
     tf.keras.layers.Dense(8,activation='relu'),
     tf.keras.layers.Dense(1,activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [41]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [42]:
#train the model
history_model=model.fit(x_train,y_train,epochs=100,validation_data=(x_test,y_test))

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.5000 - loss: 18.3068 - val_accuracy: 0.5000 - val_loss: 21.6281
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 205ms/step - accuracy: 0.5000 - loss: 17.1689 - val_accuracy: 0.5000 - val_loss: 20.3146
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 412ms/step - accuracy: 0.5000 - loss: 16.0327 - val_accuracy: 0.5000 - val_loss: 19.0025
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.5000 - loss: 14.8980 - val_accuracy: 0.5000 - val_loss: 17.6918
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.5000 - loss: 13.7588 - val_accuracy: 0.5000 - val_loss: 16.3837
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - accuracy: 0.5000 - loss: 12.6172 - val_accuracy: 0.5000 - val_loss: 15.0766
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - accuracy: 0.5000 - loss: 11.4787 - val_accuracy: 0.5000 - val_loss: 13.7704
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 189ms/step - accuracy: 0.5000 - loss: 10.3416 - val_accuracy: 0.5000 - val_loss: 12.4652
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - accuracy: 0.5000 - loss: 9.1941 - val_accuracy: 0.5000 - val_loss: 11.1613
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 265ms/step - accuracy: 0.5000 - loss: 8.0488 - val_accuracy: 0.5000 - val_loss: 9.8594
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 311ms/step - accuracy: 0.5000 - loss: 6.9037 - val_accuracy: 0.5000 - val_loss: 8.5666
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step - accuracy: 0.5000 - loss: 5.7584 - val_accuracy: 0.5000 - val_loss: 7.2868
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 207ms/step - accuracy: 0.5000 - loss: 4.5956 - val_accuracy: 0.5000 - val_loss: 6.0115
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - accuracy: 0.5000 - loss: 3.4344 - val_accuracy: 0.5000 - val_loss: 4.7379
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.5000 - loss: 2.3018 - val_accuracy: 0.5000 - val_loss: 3.4711
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 0.3750 - loss: 1.3506 - val_accuracy: 0.5000 - val_loss: 2.2094
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.6250 - loss: 1.0097 - val_accuracy: 0.5000 - val_loss: 1.2802
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.3750 - loss: 1.3988 - val_accuracy: 0.0000e+00 - val_loss: 1.0590
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.5000 - loss: 2.0299 - val_accuracy: 0.5000 - val_loss: 1.2953
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.5000 - loss: 2.5535 - val_accuracy: 0.5000 - val_loss: 1.5534
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.5000 - loss: 2.8822 - val_accuracy: 0.5000 - val_loss: 1.6781
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.5000 - loss: 3.0218 - val_accuracy: 0.5000 - val_loss: 1.6522
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.5000 - loss: 2.9943 - val_accuracy: 0.5000 - val_loss: 1.4998
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.5000 - loss: 2.8227 - val_accuracy: 0.5000 - val_loss: 1.2728
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.5000 - loss: 2.5298 - val_accuracy: 0.5000 - val_loss: 1.0709
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.5000 - loss: 2.1432 - val_accuracy: 0.0000e+00 - val_loss: 1.0494
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.5000 - loss: 1.7041 - val_accuracy: 0.5000 - val_loss: 1.3237
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6250 - loss: 1.3090 - val_accuracy: 0.5000 - val_loss: 1.8293
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.5000 - loss: 1.0902 - val_accuracy: 0.5000 - val_loss: 2.4021
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.5000 - loss: 1.0787 - val_accuracy: 0.5000 - val_loss: 2.9275
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.5000 - loss: 1.2064 - val_accuracy: 0.5000 - val_loss: 3.3480
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.3750 - loss: 1.3834 - val_accuracy: 0.5000 - val_loss: 3.6385
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.3750 - loss: 1.5337 - val_accuracy: 0.5000 - val_loss: 3.7935
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.3750 - loss: 1.6155 - val_accuracy: 0.5000 - val_loss: 3.8183
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.3750 - loss: 1.6160 - val_accuracy: 0.5000 - val_loss: 3.7250
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.3750 - loss: 1.5409 - val_accuracy: 0.5000 - val_loss: 3.5297
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.3750 - loss: 1.4096 - val_accuracy: 0.5000 - val_loss: 3.2527
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.3750 - loss: 1.2516 - val_accuracy: 0.5000 - val_loss: 2.9189
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.6250 - loss: 1.1030 - val_accuracy: 0.5000 - val_loss: 2.5583
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.5000 - loss: 0.9974 - val_accuracy: 0.5000 - val_loss: 2.2050
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.5000 - loss: 0.9543 - val_accuracy: 0.5000 - val_loss: 1.8939
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.6250 - loss: 0.9719 - val_accuracy: 0.5000 - val_loss: 1.6539
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.6250 - loss: 1.0271 - val_accuracy: 0.5000 - val_loss: 1.4993
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.7500 - loss: 1.0849 - val_accuracy: 0.5000 - val_loss: 1.4284
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6250 - loss: 1.1148 - val_accuracy: 0.5000 - val_loss: 1.4337
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.6250 - loss: 1.1051 - val_accuracy: 0.5000 - val_loss: 1.5083
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.7500 - loss: 1.0588 - val_accuracy: 0.5000 - val_loss: 1.6454
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.6250 - loss: 0.9943 - val_accuracy: 0.5000 - val_loss: 1.8312
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6250 - loss: 0.9343 - val_accuracy: 0.5000 - val_loss: 2.0434
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.5000 - loss: 0.8962 - val_accuracy: 0.5000 - val_loss: 2.2547
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.5000 - loss: 0.8878 - val_accuracy: 0.5000 - val_loss: 2.4393
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.6250 - loss: 0.9025 - val_accuracy: 0.5000 - val_loss: 2.5774
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6250 - loss: 0.9267 - val_accuracy: 0.5000 - val_loss: 2.6565
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6250 - loss: 0.9464 - val_accuracy: 0.5000 - val_loss: 2.6716
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.6250 - loss: 0.9521 - val_accuracy: 0.5000 - val_loss: 2.6247
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6250 - loss: 0.9413 - val_accuracy: 0.5000 - val_loss: 2.5237
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.6250 - loss: 0.9177 - val_accuracy: 0.5000 - val_loss: 2.3812
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.6250 - loss: 0.8892 - val_accuracy: 0.5000 - val_loss: 2.2133
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.6250 - loss: 0.8645 - val_accuracy: 0.5000 - val_loss: 2.0381
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.5000 - loss: 0.8503 - val_accuracy: 0.5000 - val_loss: 1.8736
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.5000 - loss: 0.8480 - val_accuracy: 0.5000 - val_loss: 1.7352
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.5000 - loss: 0.8543 - val_accuracy: 0.5000 - val_loss: 1.6334
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.5000 - loss: 0.8625 - val_accuracy: 0.5000 - val_loss: 1.5729
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.5000 - loss: 0.8663 - val_accuracy: 0.5000 - val_loss: 1.5534
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.5000 - loss: 0.8623 - val_accuracy: 0.5000 - val_loss: 1.5707
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.5000 - loss: 0.8512 - val_accuracy: 0.5000 - val_loss: 1.6177
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.5000 - loss: 0.8371 - val_accuracy: 0.5000 - val_loss: 1.6843
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.5000 - loss: 0.8244 - val_accuracy: 0.5000 - val_loss: 1.7585
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.5000 - loss: 0.8166 - val_accuracy: 0.5000 - val_loss: 1.8278
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.5000 - loss: 0.8141 - val_accuracy: 0.5000 - val_loss: 1.8809
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.5000 - loss: 0.8152 - val_accuracy: 0.5000 - val_loss: 1.9095
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6250 - loss: 0.8167 - val_accuracy: 0.5000 - val_loss: 1.9090
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6250 - loss: 0.8160 - val_accuracy: 0.5000 - val_loss: 1.8791
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.6250 - loss: 0.8119 - val_accuracy: 0.5000 - val_loss: 1.8233
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.6250 - loss: 0.8051 - val_accuracy: 0.5000 - val_loss: 1.7483
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.5000 - loss: 0.7973 - val_accuracy: 0.5000 - val_loss: 1.6628
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.5000 - loss: 0.7907 - val_accuracy: 0.5000 - val_loss: 1.5763
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.5000 - loss: 0.7863 - val_accuracy: 0.5000 - val_loss: 1.4974
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.5000 - loss: 0.7842 - val_accuracy: 0.5000 - val_loss: 1.4328
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6250 - loss: 0.7833 - val_accuracy: 0.5000 - val_loss: 1.3863
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.6250 - loss: 0.7820 - val_accuracy: 0.5000 - val_loss: 1.3592
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.6250 - loss: 0.7794 - val_accuracy: 0.5000 - val_loss: 1.3501
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.6250 - loss: 0.7752 - val_accuracy: 0.5000 - val_loss: 1.3556
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.6250 - loss: 0.7702 - val_accuracy: 0.5000 - val_loss: 1.3708
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.6250 - loss: 0.7654 - val_accuracy: 0.5000 - val_loss: 1.3897
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.5000 - loss: 0.7617 - val_accuracy: 0.5000 - val_loss: 1.4061
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.5000 - loss: 0.7592 - val_accuracy: 0.5000 - val_loss: 1.4146
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.5000 - loss: 0.7574 - val_accuracy: 0.5000 - val_loss: 1.4113
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.5000 - loss: 0.7556 - val_accuracy: 0.5000 - val_loss: 1.3947
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.5000 - loss: 0.7532 - val_accuracy: 0.5000 - val_loss: 1.3650
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 0.5000 - loss: 0.7502 - val_accuracy: 0.5000 - val_loss: 1.3249
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.5000 - loss: 0.7466 - val_accuracy: 0.5000 - val_loss: 1.2783
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.5000 - loss: 0.7432 - val_accuracy: 0.5000 - val_loss: 1.2300
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 0.6250 - loss: 0.7402 - val_accuracy: 0.5000 - val_loss: 1.1843
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6250 - loss: 0.7378 - val_accuracy: 0.5000 - val_loss: 1.1449
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.6250 - loss: 0.7357 - val_accuracy: 0.5000 - val_loss: 1.1138
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.6250 - loss: 0.7336 - val_accuracy: 0.5000 - val_loss: 1.0918
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.6250 - loss: 0.7312 - val_accuracy: 0.5000 - val_loss: 1.0782
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6250 - loss: 0.7285 - val_accuracy: 0.5000 - val_loss: 1.0712
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 0.6250 - loss: 0.7256 - val_accuracy: 0.5000 - val_loss: 1.0683

In [43]:
# Evaluate the model
loss,accuracy=model.evaluate(x_test,y_test)
print(f'Test Loss: {loss:.4f}')
print(f'Test Accuracy: {accuracy*100:.2f}%')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 1.0683
Test Loss: 1.0683
Test Accuracy: 50.00%

# Example 2
#*Bank Customer Exit Prediction*
#*Based on given data using Neural Network Binary Classifier find out if customer staying or leaving:(Churn=0)and leave(Churn=1)

In [44]:
bank_data=pd.read_csv('/content/sample_data/bank_churn.csv')
bank_data.head()

,CreditScore,Geography,Gender,Age,Balance,NumOfProducts,EstimatedSalary,Exited
0,600,France,Male,40,60000,1,50000,0
1,700,Spain,Female,45,70000,2,60000,0
2,800,Germany,Female,38,80000,1,70000,1
3,400,France,Male,30,30000,1,40000,1
4,550,Spain,Male,50,40000,2,42000,0

In [45]:
le = LabelEncoder()
bank_data['Gender'] = le.fit_transform(bank_data['Gender'])
bank_data=pd.get_dummies(bank_data,columns=['Geography'])

In [46]:
x=bank_data.drop('Exited',axis=1)
y=bank_data['Exited']

In [47]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [48]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [49]:
model=tf.keras.Sequential(
    [
     tf.keras.layers.Dense(16,activation='relu',input_shape=(x_train.shape[1],)),
     tf.keras.layers.Dense(8,activation='relu'),
     tf.keras.layers.Dense(1,activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [50]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [51]:
history_model=model.fit(x_train,y_train,epochs=100,validation_data=(x_test,y_test))

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.6250 - loss: 0.6723 - val_accuracy: 0.5000 - val_loss: 0.5651
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.6250 - loss: 0.6671 - val_accuracy: 0.5000 - val_loss: 0.5650
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - accuracy: 0.6250 - loss: 0.6619 - val_accuracy: 0.5000 - val_loss: 0.5649
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 287ms/step - accuracy: 0.6250 - loss: 0.6567 - val_accuracy: 0.5000 - val_loss: 0.5647
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - accuracy: 0.6250 - loss: 0.6516 - val_accuracy: 0.5000 - val_loss: 0.5645
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 0.6250 - loss: 0.6465 - val_accuracy: 0.5000 - val_loss: 0.5642
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 196ms/step - accuracy: 0.6250 - loss: 0.6415 - val_accuracy: 0.5000 - val_loss: 0.5639
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - accuracy: 0.6250 - loss: 0.6364 - val_accuracy: 0.5000 - val_loss: 0.5636
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.6250 - loss: 0.6314 - val_accuracy: 0.5000 - val_loss: 0.5632
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.6250 - loss: 0.6264 - val_accuracy: 0.5000 - val_loss: 0.5627
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6250 - loss: 0.6215 - val_accuracy: 0.5000 - val_loss: 0.5623
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6250 - loss: 0.6166 - val_accuracy: 0.5000 - val_loss: 0.5619
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6250 - loss: 0.6118 - val_accuracy: 0.5000 - val_loss: 0.5614
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.6250 - loss: 0.6070 - val_accuracy: 0.5000 - val_loss: 0.5610
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.6250 - loss: 0.6027 - val_accuracy: 0.5000 - val_loss: 0.5605
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.6250 - loss: 0.5986 - val_accuracy: 0.5000 - val_loss: 0.5600
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 0.6250 - loss: 0.5945 - val_accuracy: 0.5000 - val_loss: 0.5594
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.6250 - loss: 0.5904 - val_accuracy: 0.5000 - val_loss: 0.5587
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.6250 - loss: 0.5866 - val_accuracy: 0.5000 - val_loss: 0.5580
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.6250 - loss: 0.5829 - val_accuracy: 0.5000 - val_loss: 0.5571
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.6250 - loss: 0.5792 - val_accuracy: 0.5000 - val_loss: 0.5562
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6250 - loss: 0.5754 - val_accuracy: 0.5000 - val_loss: 0.5552
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.6250 - loss: 0.5717 - val_accuracy: 0.5000 - val_loss: 0.5542
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.6250 - loss: 0.5680 - val_accuracy: 0.5000 - val_loss: 0.5532
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.6250 - loss: 0.5643 - val_accuracy: 0.5000 - val_loss: 0.5525
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.6250 - loss: 0.5606 - val_accuracy: 0.5000 - val_loss: 0.5518
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 0.6250 - loss: 0.5569 - val_accuracy: 0.5000 - val_loss: 0.5511
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.6250 - loss: 0.5532 - val_accuracy: 0.5000 - val_loss: 0.5504
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6250 - loss: 0.5496 - val_accuracy: 0.5000 - val_loss: 0.5496
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6250 - loss: 0.5458 - val_accuracy: 0.5000 - val_loss: 0.5489
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.6250 - loss: 0.5420 - val_accuracy: 0.5000 - val_loss: 0.5482
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.7500 - loss: 0.5382 - val_accuracy: 0.5000 - val_loss: 0.5474
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.8750 - loss: 0.5344 - val_accuracy: 0.5000 - val_loss: 0.5466
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.8750 - loss: 0.5305 - val_accuracy: 0.5000 - val_loss: 0.5459
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - accuracy: 0.8750 - loss: 0.5274 - val_accuracy: 0.5000 - val_loss: 0.5450
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 0.8750 - loss: 0.5243 - val_accuracy: 0.5000 - val_loss: 0.5442
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.8750 - loss: 0.5212 - val_accuracy: 0.5000 - val_loss: 0.5433
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.8750 - loss: 0.5179 - val_accuracy: 0.5000 - val_loss: 0.5424
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.8750 - loss: 0.5147 - val_accuracy: 0.5000 - val_loss: 0.5414
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.8750 - loss: 0.5112 - val_accuracy: 0.5000 - val_loss: 0.5404
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.8750 - loss: 0.5073 - val_accuracy: 0.5000 - val_loss: 0.5392
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.8750 - loss: 0.5032 - val_accuracy: 0.5000 - val_loss: 0.5396
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 0.8750 - loss: 0.4988 - val_accuracy: 0.5000 - val_loss: 0.5407
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.8750 - loss: 0.4937 - val_accuracy: 0.5000 - val_loss: 0.5423
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - accuracy: 0.8750 - loss: 0.4884 - val_accuracy: 0.5000 - val_loss: 0.5441
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.8750 - loss: 0.4829 - val_accuracy: 0.5000 - val_loss: 0.5460
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.8750 - loss: 0.4773 - val_accuracy: 0.5000 - val_loss: 0.5483
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.8750 - loss: 0.4716 - val_accuracy: 0.5000 - val_loss: 0.5507
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.8750 - loss: 0.4658 - val_accuracy: 0.5000 - val_loss: 0.5533
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.8750 - loss: 0.4601 - val_accuracy: 0.5000 - val_loss: 0.5560
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.8750 - loss: 0.4547 - val_accuracy: 0.5000 - val_loss: 0.5589
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.8750 - loss: 0.4492 - val_accuracy: 0.5000 - val_loss: 0.5619
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.8750 - loss: 0.4438 - val_accuracy: 0.5000 - val_loss: 0.5650
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.8750 - loss: 0.4382 - val_accuracy: 0.5000 - val_loss: 0.5682
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.8750 - loss: 0.4328 - val_accuracy: 0.5000 - val_loss: 0.5716
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.8750 - loss: 0.4272 - val_accuracy: 0.5000 - val_loss: 0.5751
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.4216 - val_accuracy: 0.5000 - val_loss: 0.5786
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.4161 - val_accuracy: 0.5000 - val_loss: 0.5822
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.4106 - val_accuracy: 0.5000 - val_loss: 0.5859
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.4052 - val_accuracy: 0.5000 - val_loss: 0.5896
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 1.0000 - loss: 0.3997 - val_accuracy: 0.5000 - val_loss: 0.5934
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.3943 - val_accuracy: 0.5000 - val_loss: 0.5971
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - accuracy: 1.0000 - loss: 0.3890 - val_accuracy: 0.5000 - val_loss: 0.6007
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 1.0000 - loss: 0.3837 - val_accuracy: 0.5000 - val_loss: 0.6045
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 1.0000 - loss: 0.3785 - val_accuracy: 0.5000 - val_loss: 0.6093
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.3734 - val_accuracy: 0.5000 - val_loss: 0.6143
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.3685 - val_accuracy: 0.5000 - val_loss: 0.6194
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.3635 - val_accuracy: 0.5000 - val_loss: 0.6245
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.3586 - val_accuracy: 0.5000 - val_loss: 0.6298
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 1.0000 - loss: 0.3538 - val_accuracy: 0.5000 - val_loss: 0.6353
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.3489 - val_accuracy: 0.5000 - val_loss: 0.6409
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 1.0000 - loss: 0.3439 - val_accuracy: 0.5000 - val_loss: 0.6465
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 1.0000 - loss: 0.3388 - val_accuracy: 0.5000 - val_loss: 0.6522
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 1.0000 - loss: 0.3336 - val_accuracy: 0.5000 - val_loss: 0.6579
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.3283 - val_accuracy: 0.5000 - val_loss: 0.6638
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 1.0000 - loss: 0.3231 - val_accuracy: 0.5000 - val_loss: 0.6696
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 1.0000 - loss: 0.3178 - val_accuracy: 0.5000 - val_loss: 0.6755
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 1.0000 - loss: 0.3127 - val_accuracy: 0.5000 - val_loss: 0.6815
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 1.0000 - loss: 0.3075 - val_accuracy: 0.5000 - val_loss: 0.6875
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 1.0000 - loss: 0.3023 - val_accuracy: 0.5000 - val_loss: 0.6935
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.2973 - val_accuracy: 0.5000 - val_loss: 0.6995
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 1.0000 - loss: 0.2923 - val_accuracy: 0.5000 - val_loss: 0.7055
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 1.0000 - loss: 0.2871 - val_accuracy: 0.5000 - val_loss: 0.7116
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 1.0000 - loss: 0.2819 - val_accuracy: 0.5000 - val_loss: 0.7177
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 1.0000 - loss: 0.2767 - val_accuracy: 0.5000 - val_loss: 0.7239
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 1.0000 - loss: 0.2716 - val_accuracy: 0.5000 - val_loss: 0.7300
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.2665 - val_accuracy: 0.5000 - val_loss: 0.7361
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.2615 - val_accuracy: 0.5000 - val_loss: 0.7422
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 1.0000 - loss: 0.2568 - val_accuracy: 0.5000 - val_loss: 0.7484
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 1.0000 - loss: 0.2520 - val_accuracy: 0.5000 - val_loss: 0.7547
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 1.0000 - loss: 0.2472 - val_accuracy: 0.5000 - val_loss: 0.7610
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 1.0000 - loss: 0.2428 - val_accuracy: 0.5000 - val_loss: 0.7670
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 1.0000 - loss: 0.2389 - val_accuracy: 0.5000 - val_loss: 0.7728
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 1.0000 - loss: 0.2350 - val_accuracy: 0.5000 - val_loss: 0.7782
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 1.0000 - loss: 0.2312 - val_accuracy: 0.5000 - val_loss: 0.7835
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 1.0000 - loss: 0.2273 - val_accuracy: 0.5000 - val_loss: 0.7886
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.2235 - val_accuracy: 0.5000 - val_loss: 0.7935
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.2197 - val_accuracy: 0.5000 - val_loss: 0.7982
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 1.0000 - loss: 0.2160 - val_accuracy: 0.5000 - val_loss: 0.8028
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 1.0000 - loss: 0.2123 - val_accuracy: 0.5000 - val_loss: 0.8071

In [52]:
loss,accuracy=model.evaluate(x_test,y_test)
print(f'Test Loss: {loss:.4f}')
print(f'Test Accuracy: {accuracy*100:.2f}%')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.5000 - loss: 0.8071
Test Loss: 0.8071
Test Accuracy: 50.00%

In [53]:
#predict new customer

In [57]:
new_customer = pd.DataFrame({
    "CreditScore": [720],
    "Geography": ["France"],
    "Gender": ["Male"],
    "Age": [42],
    "Balance": [62000],
    "NumOfProducts": [1],
    "EstimatedSalary": [55000]
})

# Encode and scale same as before
new_customer["Gender"] = le.transform(new_customer["Gender"])
new_customer = pd.get_dummies(new_customer, columns=["Geography"], drop_first=True)

# Add missing dummy columns
for col in [c for c in x.columns if c not in new_customer.columns]:
    new_customer[col] = 0

new_customer = new_customer[x.columns]  # same order
new_scaled = scaler.transform(new_customer)


pred =model.predict(new_scaled)
if pred[0][0] > 0.5:
    print("Customer will leave")
    print(pred[0][0])
else:
    print("Customer will stay")
    print(pred[0][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
Customer will stay
0.45763567